### ISSUE TITLE
Update 9.10.16

### ISSUE THREAD

**Issue by GuyMonkey** [PietsHost/SoftwareInc.Deutsch#15]
Hi,

ich bin erstmal mit den Übersetzungen fertig.
Weitere Fehler, wenn ich welche finde, werde ich erst einmal sammeln und dann später gesammelt einstellen.

Das Tutorial muß in den bereits übersetzten Teilen teilweise neu gemacht werden, weil sich die zugrunde liegenden Spielmechaniken verändert haben. Dazu komme ich aber vorerst nicht, da das einiges an Zeit erfordert.

Grüße,
GuyMonkey

**Comment by PietsHost** [comment]
Alles klar. Vielen Dank für deine Unterstützung!
