### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by GuyMonkey** [PietsHost/SoftwareInc.Deutsch#17]
Ich bin gerade dabei, das Tutorial neu zu übersetzen, weil sich da doch einiges geändert hat und ettliches noch gar nicht übersetzt war. Ich bin etwa bei der Hälfte und denke, daß ich in wenigen Tagen, evtl. bis morgen, damit fertig werden werde.

**Comment by GuyMonkey** [comment]
Ich bin mit dem Tutorial fertig.
Damit ist die Version 9.11.2 erst einmal fertig.

**Comment by PietsHost** [comment]
Super, vielen Dank für die Unterstützung!
